### ISSUE TITLE
Error on DE extraction

### ISSUE THREAD

**Issue by fantinuoli** [fantinuoli/nlpAPI#7]
When extracting from DE, I get the following error:

    new_matcher.add(f"term{i}", add_to_counter, pattern)
    File "spacy/matcher/matcher.pyx", line 76, in spacy.matcher.matcher.Matcher.add
    TypeError: add() takes exactly 2 positional arguments (3 given)

**Comment by dblandan** [comment]
I believe this is caused by a spaCy v3 model being used with spaCy v2 code.  Please try `pipenv --rm` then re-install requirements; this should fix this error.
